services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=product_api_user
      - POSTGRES_PASSWORD=product_api_pwd
      - POSTGRES_DB=product_db
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5878:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U product_api_user -d product_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - product-api-network

networks:
  product-api-network:
    driver: bridge