services:
  product-api:
    image: 'product-api:latest'
    build:
      context: .
    container_name: product-api
    depends_on:
      - db
    ports:
      - "6868:8080"
      - "6869:8081"
    environment:
      - FLYWAY_DB_PASSWORD=${PRODUCT_DB_ADMIN_PASSWORD}
      - SA_DB_PASSWORD=${PRODUCT_DB_API_PASSWORD}

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=product_api_user
      - POSTGRES_PASSWORD=${PRODUCT_DB_ADMIN_PASSWORD}
      - POSTGRES_DB=product_api_db
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"