services:
  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=product_api_user
      - POSTGRES_PASSWORD=${PRODUCT_DB_ADMIN_PASSWORD}
      - POSTGRES_DB=product_db
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "5433:5432"
    networks:
      - product-api-network

networks:
  product-api-network:
    driver: bridge