security-properties:
  encryptionSecretKey: 1234567890123456

spring:
  application:
    name: product-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/product_db
    username: service_account
    password: ${SA_DB_PASSWORD}

    hikari:
      connectionInitSql: select set_config('encryption.key', '${security-properties.encryptionSecretKey}', false)

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
      format_sql: true
      use_sql_comments: true
      generate_statistics: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: true # don't fail if the V2 script needs run before the V1 script
    ignore-migration-patterns: "*:missing" # don't fail if a migration previously seen (potentially from a different branch) isn't seen now

    # use specific flyway db user that has elevated privileges
    url: jdbc:postgresql://postgres:5432/product_db
    user: product_api_user
    password: ${FLYWAY_DB_PASSWORD}

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html

  docker:
    compose:
      skip:
        in-tests: false

management:
  server:
    port: 8081
    ssl.enabled: false
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: '*'
  endpoint:
    info.enabled: true
    loggers.enabled: true
    health:
      enabled: true
      show-details: always

logging:
  level:
    org.springframework.jdbc.datasource: DEBUG
    org.springframework.boot.jdbc.DataSourceInitialization: DEBUG
